<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\id_domisilis;

class DomisilisSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('id_domisilis')->insert(['id' => 1101, 'provinces_id' => 11, 'domisili_name' => 'SIMEULUE',]);
        DB::table('id_domisilis')->insert(['id' => 1102, 'provinces_id' => 11, 'domisili_name' => 'ACEH SINGKIL',]);
        DB::table('id_domisilis')->insert(['id' => 1103, 'provinces_id' => 11, 'domisili_name' => 'ACEH SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 1104, 'provinces_id' => 11, 'domisili_name' => 'ACEH TENGGARA',]);
        DB::table('id_domisilis')->insert(['id' => 1105, 'provinces_id' => 11, 'domisili_name' => 'ACEH TIMUR',]);
        DB::table('id_domisilis')->insert(['id' => 1106, 'provinces_id' => 11, 'domisili_name' => 'ACEH TENGAH',]);
        DB::table('id_domisilis')->insert(['id' => 1107, 'provinces_id' => 11, 'domisili_name' => 'ACEH BARAT',]);
        DB::table('id_domisilis')->insert(['id' => 1108, 'provinces_id' => 11, 'domisili_name' => 'ACEH BESAR',]);
        DB::table('id_domisilis')->insert(['id' => 1109, 'provinces_id' => 11, 'domisili_name' => 'PIDIE',]);
        DB::table('id_domisilis')->insert(['id' => 1110, 'provinces_id' => 11, 'domisili_name' => 'BIREUEN',]);
        DB::table('id_domisilis')->insert(['id' => 1111, 'provinces_id' => 11, 'domisili_name' => 'ACEH UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 1112, 'provinces_id' => 11, 'domisili_name' => 'ACEH BARAT DAYA',]);
        DB::table('id_domisilis')->insert(['id' => 1113, 'provinces_id' => 11, 'domisili_name' => 'GAYO LUES',]);
        DB::table('id_domisilis')->insert(['id' => 1114, 'provinces_id' => 11, 'domisili_name' => 'ACEH TAMIANG',]);
        DB::table('id_domisilis')->insert(['id' => 1115, 'provinces_id' => 11, 'domisili_name' => 'NAGAN RAYA',]);
        DB::table('id_domisilis')->insert(['id' => 1116, 'provinces_id' => 11, 'domisili_name' => 'ACEH JAYA',]);
        DB::table('id_domisilis')->insert(['id' => 1117, 'provinces_id' => 11, 'domisili_name' => 'BENER MERIAH',]);
        DB::table('id_domisilis')->insert(['id' => 1118, 'provinces_id' => 11, 'domisili_name' => 'PIDIE JAYA',]);
        DB::table('id_domisilis')->insert(['id' => 1171, 'provinces_id' => 11, 'domisili_name' => 'BANDA ACEH',]);
        DB::table('id_domisilis')->insert(['id' => 1172, 'provinces_id' => 11, 'domisili_name' => 'SABANG',]);
        DB::table('id_domisilis')->insert(['id' => 1173, 'provinces_id' => 11, 'domisili_name' => 'LANGSA',]);
        DB::table('id_domisilis')->insert(['id' => 1174, 'provinces_id' => 11, 'domisili_name' => 'LHOKSEUMAWE',]);
        DB::table('id_domisilis')->insert(['id' => 1175, 'provinces_id' => 11, 'domisili_name' => 'SUBULUSSALAM',]);
        DB::table('id_domisilis')->insert(['id' => 1201, 'provinces_id' => 12, 'domisili_name' => 'NIAS',]);
        DB::table('id_domisilis')->insert(['id' => 1202, 'provinces_id' => 12, 'domisili_name' => 'MANDAILING NATAL',]);
        DB::table('id_domisilis')->insert(['id' => 1203, 'provinces_id' => 12, 'domisili_name' => 'TAPANULI SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 1204, 'provinces_id' => 12, 'domisili_name' => 'TAPANULI TENGAH',]);
        DB::table('id_domisilis')->insert(['id' => 1205, 'provinces_id' => 12, 'domisili_name' => 'TAPANULI UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 1206, 'provinces_id' => 12, 'domisili_name' => 'TOBA SAMOSIR',]);
        DB::table('id_domisilis')->insert(['id' => 1207, 'provinces_id' => 12, 'domisili_name' => 'LABUHAN BATU',]);
        DB::table('id_domisilis')->insert(['id' => 1208, 'provinces_id' => 12, 'domisili_name' => 'ASAHAN',]);
        DB::table('id_domisilis')->insert(['id' => 1209, 'provinces_id' => 12, 'domisili_name' => 'SIMALUNGUN',]);
        DB::table('id_domisilis')->insert(['id' => 1210, 'provinces_id' => 12, 'domisili_name' => 'DAIRI',]);
        DB::table('id_domisilis')->insert(['id' => 1211, 'provinces_id' => 12, 'domisili_name' => 'KARO',]);
        DB::table('id_domisilis')->insert(['id' => 1212, 'provinces_id' => 12, 'domisili_name' => 'DELI SERDANG',]);
        DB::table('id_domisilis')->insert(['id' => 1213, 'provinces_id' => 12, 'domisili_name' => 'LANGKAT',]);
        DB::table('id_domisilis')->insert(['id' => 1214, 'provinces_id' => 12, 'domisili_name' => 'NIAS SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 1215, 'provinces_id' => 12, 'domisili_name' => 'HUMBANG HASUNDUTAN',]);
        DB::table('id_domisilis')->insert(['id' => 1216, 'provinces_id' => 12, 'domisili_name' => 'PAKPAK BHARAT',]);
        DB::table('id_domisilis')->insert(['id' => 1217, 'provinces_id' => 12, 'domisili_name' => 'SAMOSIR',]);
        DB::table('id_domisilis')->insert(['id' => 1218, 'provinces_id' => 12, 'domisili_name' => 'SERDANG BEDAGAI',]);
        DB::table('id_domisilis')->insert(['id' => 1219, 'provinces_id' => 12, 'domisili_name' => 'BATU BARA',]);
        DB::table('id_domisilis')->insert(['id' => 1220, 'provinces_id' => 12, 'domisili_name' => 'PADANG LAWAS UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 1221, 'provinces_id' => 12, 'domisili_name' => 'PADANG LAWAS',]);
        DB::table('id_domisilis')->insert(['id' => 1222, 'provinces_id' => 12, 'domisili_name' => 'LABUHAN BATU SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 1223, 'provinces_id' => 12, 'domisili_name' => 'LABUHAN BATU UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 1224, 'provinces_id' => 12, 'domisili_name' => 'NIAS UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 1225, 'provinces_id' => 12, 'domisili_name' => 'NIAS BARAT',]);
        DB::table('id_domisilis')->insert(['id' => 1271, 'provinces_id' => 12, 'domisili_name' => 'SIBOLGA',]);
        DB::table('id_domisilis')->insert(['id' => 1272, 'provinces_id' => 12, 'domisili_name' => 'TANJUNG BALAI',]);
        DB::table('id_domisilis')->insert(['id' => 1273, 'provinces_id' => 12, 'domisili_name' => 'PEMATANG SIANTAR',]);
        DB::table('id_domisilis')->insert(['id' => 1274, 'provinces_id' => 12, 'domisili_name' => 'TEBING TINGGI',]);
        DB::table('id_domisilis')->insert(['id' => 1275, 'provinces_id' => 12, 'domisili_name' => 'MEDAN',]);
        DB::table('id_domisilis')->insert(['id' => 1276, 'provinces_id' => 12, 'domisili_name' => 'BINJAI',]);
        DB::table('id_domisilis')->insert(['id' => 1277, 'provinces_id' => 12, 'domisili_name' => 'PADANGSIDIMPUAN',]);
        DB::table('id_domisilis')->insert(['id' => 1278, 'provinces_id' => 12, 'domisili_name' => 'GUNUNGSITOLI',]);
        DB::table('id_domisilis')->insert(['id' => 1301, 'provinces_id' => 13, 'domisili_name' => 'KEPULAUAN MENTAWAI',]);
        DB::table('id_domisilis')->insert(['id' => 1302, 'provinces_id' => 13, 'domisili_name' => 'PESISIR SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 1303, 'provinces_id' => 13, 'domisili_name' => 'SOLOK',]);
        DB::table('id_domisilis')->insert(['id' => 1304, 'provinces_id' => 13, 'domisili_name' => 'SIJUNJUNG',]);
        DB::table('id_domisilis')->insert(['id' => 1305, 'provinces_id' => 13, 'domisili_name' => 'TANAH DATAR',]);
        DB::table('id_domisilis')->insert(['id' => 1306, 'provinces_id' => 13, 'domisili_name' => 'PADANG PARIAMAN',]);
        DB::table('id_domisilis')->insert(['id' => 1307, 'provinces_id' => 13, 'domisili_name' => 'AGAM',]);
        DB::table('id_domisilis')->insert(['id' => 1308, 'provinces_id' => 13, 'domisili_name' => 'LIMA PULUH KOTA',]);
        DB::table('id_domisilis')->insert(['id' => 1309, 'provinces_id' => 13, 'domisili_name' => 'PASAMAN',]);
        DB::table('id_domisilis')->insert(['id' => 1310, 'provinces_id' => 13, 'domisili_name' => 'SOLOK SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 1311, 'provinces_id' => 13, 'domisili_name' => 'DHARMASRAYA',]);
        DB::table('id_domisilis')->insert(['id' => 1312, 'provinces_id' => 13, 'domisili_name' => 'PASAMAN BARAT',]);
        DB::table('id_domisilis')->insert(['id' => 1371, 'provinces_id' => 13, 'domisili_name' => 'PADANG',]);
        DB::table('id_domisilis')->insert(['id' => 1372, 'provinces_id' => 13, 'domisili_name' => 'SOLOK',]);
        DB::table('id_domisilis')->insert(['id' => 1373, 'provinces_id' => 13, 'domisili_name' => 'SAWAH LUNTO',]);
        DB::table('id_domisilis')->insert(['id' => 1374, 'provinces_id' => 13, 'domisili_name' => 'PADANG PANJANG',]);
        DB::table('id_domisilis')->insert(['id' => 1375, 'provinces_id' => 13, 'domisili_name' => 'BUKITTINGGI',]);
        DB::table('id_domisilis')->insert(['id' => 1376, 'provinces_id' => 13, 'domisili_name' => 'PAYAKUMBUH',]);
        DB::table('id_domisilis')->insert(['id' => 1377, 'provinces_id' => 13, 'domisili_name' => 'PARIAMAN',]);
        DB::table('id_domisilis')->insert(['id' => 1401, 'provinces_id' => 14, 'domisili_name' => 'KUANTAN SINGINGI',]);
        DB::table('id_domisilis')->insert(['id' => 1402, 'provinces_id' => 14, 'domisili_name' => 'INDRAGIRI HULU',]);
        DB::table('id_domisilis')->insert(['id' => 1403, 'provinces_id' => 14, 'domisili_name' => 'INDRAGIRI HILIR',]);
        DB::table('id_domisilis')->insert(['id' => 1404, 'provinces_id' => 14, 'domisili_name' => 'PELALAWAN',]);
        DB::table('id_domisilis')->insert(['id' => 1405, 'provinces_id' => 14, 'domisili_name' => 'S I A K',]);
        DB::table('id_domisilis')->insert(['id' => 1406, 'provinces_id' => 14, 'domisili_name' => 'KAMPAR',]);
        DB::table('id_domisilis')->insert(['id' => 1407, 'provinces_id' => 14, 'domisili_name' => 'ROKAN HULU',]);
        DB::table('id_domisilis')->insert(['id' => 1408, 'provinces_id' => 14, 'domisili_name' => 'BENGKALIS',]);
        DB::table('id_domisilis')->insert(['id' => 1409, 'provinces_id' => 14, 'domisili_name' => 'ROKAN HILIR',]);
        DB::table('id_domisilis')->insert(['id' => 1410, 'provinces_id' => 14, 'domisili_name' => 'KEPULAUAN MERANTI',]);
        DB::table('id_domisilis')->insert(['id' => 1471, 'provinces_id' => 14, 'domisili_name' => 'PEKANBARU',]);
        DB::table('id_domisilis')->insert(['id' => 1473, 'provinces_id' => 14, 'domisili_name' => 'D U M A I',]);
        DB::table('id_domisilis')->insert(['id' => 1501, 'provinces_id' => 15, 'domisili_name' => 'KERINCI',]);
        DB::table('id_domisilis')->insert(['id' => 1502, 'provinces_id' => 15, 'domisili_name' => 'MERANGIN',]);
        DB::table('id_domisilis')->insert(['id' => 1503, 'provinces_id' => 15, 'domisili_name' => 'SAROLANGUN',]);
        DB::table('id_domisilis')->insert(['id' => 1504, 'provinces_id' => 15, 'domisili_name' => 'BATANG HARI',]);
        DB::table('id_domisilis')->insert(['id' => 1505, 'provinces_id' => 15, 'domisili_name' => 'MUARO JAMBI',]);
        DB::table('id_domisilis')->insert(['id' => 1506, 'provinces_id' => 15, 'domisili_name' => 'TANJUNG JABUNG TIMUR',]);
        DB::table('id_domisilis')->insert(['id' => 1507, 'provinces_id' => 15, 'domisili_name' => 'TANJUNG JABUNG BARAT',]);
        DB::table('id_domisilis')->insert(['id' => 1508, 'provinces_id' => 15, 'domisili_name' => 'TEBO',]);
        DB::table('id_domisilis')->insert(['id' => 1509, 'provinces_id' => 15, 'domisili_name' => 'BUNGO',]);
        DB::table('id_domisilis')->insert(['id' => 1571, 'provinces_id' => 15, 'domisili_name' => 'JAMBI',]);
        DB::table('id_domisilis')->insert(['id' => 1572, 'provinces_id' => 15, 'domisili_name' => 'SUNGAI PENUH',]);
        DB::table('id_domisilis')->insert(['id' => 1601, 'provinces_id' => 16, 'domisili_name' => 'OGAN KOMERING ULU',]);
        DB::table('id_domisilis')->insert(['id' => 1602, 'provinces_id' => 16, 'domisili_name' => 'OGAN KOMERING ILIR',]);
        DB::table('id_domisilis')->insert(['id' => 1603, 'provinces_id' => 16, 'domisili_name' => 'MUARA ENIM',]);
        DB::table('id_domisilis')->insert(['id' => 1604, 'provinces_id' => 16, 'domisili_name' => 'LAHAT',]);
        DB::table('id_domisilis')->insert(['id' => 1605, 'provinces_id' => 16, 'domisili_name' => 'MUSI RAWAS',]);
        DB::table('id_domisilis')->insert(['id' => 1606, 'provinces_id' => 16, 'domisili_name' => 'MUSI BANYUASIN',]);
        DB::table('id_domisilis')->insert(['id' => 1607, 'provinces_id' => 16, 'domisili_name' => 'BANYU ASIN',]);
        DB::table('id_domisilis')->insert(['id' => 1608, 'provinces_id' => 16, 'domisili_name' => 'OGAN KOMERING ULU SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 1609, 'provinces_id' => 16, 'domisili_name' => 'OGAN KOMERING ULU TIMUR',]);
        DB::table('id_domisilis')->insert(['id' => 1610, 'provinces_id' => 16, 'domisili_name' => 'OGAN ILIR',]);
        DB::table('id_domisilis')->insert(['id' => 1611, 'provinces_id' => 16, 'domisili_name' => 'EMPAT LAWANG',]);
        DB::table('id_domisilis')->insert(['id' => 1612, 'provinces_id' => 16, 'domisili_name' => 'PENUKAL ABAB LEMATANG ILIR',]);
        DB::table('id_domisilis')->insert(['id' => 1613, 'provinces_id' => 16, 'domisili_name' => 'MUSI RAWAS UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 1671, 'provinces_id' => 16, 'domisili_name' => 'PALEMBANG',]);
        DB::table('id_domisilis')->insert(['id' => 1672, 'provinces_id' => 16, 'domisili_name' => 'PRABUMULIH',]);
        DB::table('id_domisilis')->insert(['id' => 1673, 'provinces_id' => 16, 'domisili_name' => 'PAGAR ALAM',]);
        DB::table('id_domisilis')->insert(['id' => 1674, 'provinces_id' => 16, 'domisili_name' => 'LUBUKLINGGAU',]);
        DB::table('id_domisilis')->insert(['id' => 1701, 'provinces_id' => 17, 'domisili_name' => 'BENGKULU SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 1702, 'provinces_id' => 17, 'domisili_name' => 'REJANG LEBONG',]);
        DB::table('id_domisilis')->insert(['id' => 1703, 'provinces_id' => 17, 'domisili_name' => 'BENGKULU UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 1704, 'provinces_id' => 17, 'domisili_name' => 'KAUR',]);
        DB::table('id_domisilis')->insert(['id' => 1705, 'provinces_id' => 17, 'domisili_name' => 'SELUMA',]);
        DB::table('id_domisilis')->insert(['id' => 1706, 'provinces_id' => 17, 'domisili_name' => 'MUKOMUKO',]);
        DB::table('id_domisilis')->insert(['id' => 1707, 'provinces_id' => 17, 'domisili_name' => 'LEBONG',]);
        DB::table('id_domisilis')->insert(['id' => 1708, 'provinces_id' => 17, 'domisili_name' => 'KEPAHIANG',]);
        DB::table('id_domisilis')->insert(['id' => 1709, 'provinces_id' => 17, 'domisili_name' => 'BENGKULU TENGAH',]);
        DB::table('id_domisilis')->insert(['id' => 1771, 'provinces_id' => 17, 'domisili_name' => 'BENGKULU',]);
        DB::table('id_domisilis')->insert(['id' => 1801, 'provinces_id' => 18, 'domisili_name' => 'LAMPUNG BARAT',]);
        DB::table('id_domisilis')->insert(['id' => 1802, 'provinces_id' => 18, 'domisili_name' => 'TANGGAMUS',]);
        DB::table('id_domisilis')->insert(['id' => 1803, 'provinces_id' => 18, 'domisili_name' => 'LAMPUNG SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 1804, 'provinces_id' => 18, 'domisili_name' => 'LAMPUNG TIMUR',]);
        DB::table('id_domisilis')->insert(['id' => 1805, 'provinces_id' => 18, 'domisili_name' => 'LAMPUNG TENGAH',]);
        DB::table('id_domisilis')->insert(['id' => 1806, 'provinces_id' => 18, 'domisili_name' => 'LAMPUNG UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 1807, 'provinces_id' => 18, 'domisili_name' => 'WAY KANAN',]);
        DB::table('id_domisilis')->insert(['id' => 1808, 'provinces_id' => 18, 'domisili_name' => 'TULANGBAWANG',]);
        DB::table('id_domisilis')->insert(['id' => 1809, 'provinces_id' => 18, 'domisili_name' => 'PESAWARAN',]);
        DB::table('id_domisilis')->insert(['id' => 1810, 'provinces_id' => 18, 'domisili_name' => 'PRINGSEWU',]);
        DB::table('id_domisilis')->insert(['id' => 1811, 'provinces_id' => 18, 'domisili_name' => 'MESUJI',]);
        DB::table('id_domisilis')->insert(['id' => 1812, 'provinces_id' => 18, 'domisili_name' => 'TULANG BAWANG BARAT',]);
        DB::table('id_domisilis')->insert(['id' => 1813, 'provinces_id' => 18, 'domisili_name' => 'PESISIR BARAT',]);
        DB::table('id_domisilis')->insert(['id' => 1871, 'provinces_id' => 18, 'domisili_name' => 'BANDAR LAMPUNG',]);
        DB::table('id_domisilis')->insert(['id' => 1872, 'provinces_id' => 18, 'domisili_name' => 'METRO',]);
        DB::table('id_domisilis')->insert(['id' => 1901, 'provinces_id' => 19, 'domisili_name' => 'BANGKA',]);
        DB::table('id_domisilis')->insert(['id' => 1902, 'provinces_id' => 19, 'domisili_name' => 'BELITUNG',]);
        DB::table('id_domisilis')->insert(['id' => 1903, 'provinces_id' => 19, 'domisili_name' => 'BANGKA BARAT',]);
        DB::table('id_domisilis')->insert(['id' => 1904, 'provinces_id' => 19, 'domisili_name' => 'BANGKA TENGAH',]);
        DB::table('id_domisilis')->insert(['id' => 1905, 'provinces_id' => 19, 'domisili_name' => 'BANGKA SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 1906, 'provinces_id' => 19, 'domisili_name' => 'BELITUNG TIMUR',]);
        DB::table('id_domisilis')->insert(['id' => 1971, 'provinces_id' => 19, 'domisili_name' => 'PANGKAL PINANG',]);
        DB::table('id_domisilis')->insert(['id' => 2101, 'provinces_id' => 21, 'domisili_name' => 'KARIMUN',]);
        DB::table('id_domisilis')->insert(['id' => 2102, 'provinces_id' => 21, 'domisili_name' => 'BINTAN',]);
        DB::table('id_domisilis')->insert(['id' => 2103, 'provinces_id' => 21, 'domisili_name' => 'NATUNA',]);
        DB::table('id_domisilis')->insert(['id' => 2104, 'provinces_id' => 21, 'domisili_name' => 'LINGGA',]);
        DB::table('id_domisilis')->insert(['id' => 2105, 'provinces_id' => 21, 'domisili_name' => 'KEPULAUAN ANAMBAS',]);
        DB::table('id_domisilis')->insert(['id' => 2171, 'provinces_id' => 21, 'domisili_name' => 'BATAM',]);
        DB::table('id_domisilis')->insert(['id' => 2172, 'provinces_id' => 21, 'domisili_name' => 'TANJUNG PINANG',]);
        DB::table('id_domisilis')->insert(['id' => 3101, 'provinces_id' => 31, 'domisili_name' => 'KEPULAUAN SERIBU',]);
        DB::table('id_domisilis')->insert(['id' => 3171, 'provinces_id' => 31, 'domisili_name' => 'JAKARTA SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 3172, 'provinces_id' => 31, 'domisili_name' => 'JAKARTA TIMUR',]);
        DB::table('id_domisilis')->insert(['id' => 3173, 'provinces_id' => 31, 'domisili_name' => 'JAKARTA PUSAT',]);
        DB::table('id_domisilis')->insert(['id' => 3174, 'provinces_id' => 31, 'domisili_name' => 'JAKARTA BARAT',]);
        DB::table('id_domisilis')->insert(['id' => 3175, 'provinces_id' => 31, 'domisili_name' => 'JAKARTA UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 3201, 'provinces_id' => 32, 'domisili_name' => 'BOGOR',]);
        DB::table('id_domisilis')->insert(['id' => 3202, 'provinces_id' => 32, 'domisili_name' => 'SUKABUMI',]);
        DB::table('id_domisilis')->insert(['id' => 3203, 'provinces_id' => 32, 'domisili_name' => 'CIANJUR',]);
        DB::table('id_domisilis')->insert(['id' => 3204, 'provinces_id' => 32, 'domisili_name' => 'BANDUNG',]);
        DB::table('id_domisilis')->insert(['id' => 3205, 'provinces_id' => 32, 'domisili_name' => 'GARUT',]);
        DB::table('id_domisilis')->insert(['id' => 3206, 'provinces_id' => 32, 'domisili_name' => 'TASIKMALAYA',]);
        DB::table('id_domisilis')->insert(['id' => 3207, 'provinces_id' => 32, 'domisili_name' => 'CIAMIS',]);
        DB::table('id_domisilis')->insert(['id' => 3208, 'provinces_id' => 32, 'domisili_name' => 'KUNINGAN',]);
        DB::table('id_domisilis')->insert(['id' => 3209, 'provinces_id' => 32, 'domisili_name' => 'CIREBON',]);
        DB::table('id_domisilis')->insert(['id' => 3210, 'provinces_id' => 32, 'domisili_name' => 'MAJALENGKA',]);
        DB::table('id_domisilis')->insert(['id' => 3211, 'provinces_id' => 32, 'domisili_name' => 'SUMEDANG',]);
        DB::table('id_domisilis')->insert(['id' => 3212, 'provinces_id' => 32, 'domisili_name' => 'INDRAMAYU',]);
        DB::table('id_domisilis')->insert(['id' => 3213, 'provinces_id' => 32, 'domisili_name' => 'SUBANG',]);
        DB::table('id_domisilis')->insert(['id' => 3214, 'provinces_id' => 32, 'domisili_name' => 'PURWAKARTA',]);
        DB::table('id_domisilis')->insert(['id' => 3215, 'provinces_id' => 32, 'domisili_name' => 'KARAWANG',]);
        DB::table('id_domisilis')->insert(['id' => 3216, 'provinces_id' => 32, 'domisili_name' => 'BEKASI',]);
        DB::table('id_domisilis')->insert(['id' => 3217, 'provinces_id' => 32, 'domisili_name' => 'BANDUNG BARAT',]);
        DB::table('id_domisilis')->insert(['id' => 3218, 'provinces_id' => 32, 'domisili_name' => 'PANGANDARAN',]);
        DB::table('id_domisilis')->insert(['id' => 3271, 'provinces_id' => 32, 'domisili_name' => 'BOGOR',]);
        DB::table('id_domisilis')->insert(['id' => 3272, 'provinces_id' => 32, 'domisili_name' => 'SUKABUMI',]);
        DB::table('id_domisilis')->insert(['id' => 3273, 'provinces_id' => 32, 'domisili_name' => 'BANDUNG',]);
        DB::table('id_domisilis')->insert(['id' => 3274, 'provinces_id' => 32, 'domisili_name' => 'CIREBON',]);
        DB::table('id_domisilis')->insert(['id' => 3275, 'provinces_id' => 32, 'domisili_name' => 'BEKASI',]);
        DB::table('id_domisilis')->insert(['id' => 3276, 'provinces_id' => 32, 'domisili_name' => 'DEPOK',]);
        DB::table('id_domisilis')->insert(['id' => 3277, 'provinces_id' => 32, 'domisili_name' => 'CIMAHI',]);
        DB::table('id_domisilis')->insert(['id' => 3278, 'provinces_id' => 32, 'domisili_name' => 'TASIKMALAYA',]);
        DB::table('id_domisilis')->insert(['id' => 3279, 'provinces_id' => 32, 'domisili_name' => 'BANJAR',]);
        DB::table('id_domisilis')->insert(['id' => 3301, 'provinces_id' => 33, 'domisili_name' => 'CILACAP',]);
        DB::table('id_domisilis')->insert(['id' => 3302, 'provinces_id' => 33, 'domisili_name' => 'BANYUMAS',]);
        DB::table('id_domisilis')->insert(['id' => 3303, 'provinces_id' => 33, 'domisili_name' => 'PURBALINGGA',]);
        DB::table('id_domisilis')->insert(['id' => 3304, 'provinces_id' => 33, 'domisili_name' => 'BANJARNEGARA',]);
        DB::table('id_domisilis')->insert(['id' => 3305, 'provinces_id' => 33, 'domisili_name' => 'KEBUMEN',]);
        DB::table('id_domisilis')->insert(['id' => 3306, 'provinces_id' => 33, 'domisili_name' => 'PURWOREJO',]);
        DB::table('id_domisilis')->insert(['id' => 3307, 'provinces_id' => 33, 'domisili_name' => 'WONOSOBO',]);
        DB::table('id_domisilis')->insert(['id' => 3308, 'provinces_id' => 33, 'domisili_name' => 'MAGELANG',]);
        DB::table('id_domisilis')->insert(['id' => 3309, 'provinces_id' => 33, 'domisili_name' => 'BOYOLALI',]);
        DB::table('id_domisilis')->insert(['id' => 3310, 'provinces_id' => 33, 'domisili_name' => 'KLATEN',]);
        DB::table('id_domisilis')->insert(['id' => 3311, 'provinces_id' => 33, 'domisili_name' => 'SUKOHARJO',]);
        DB::table('id_domisilis')->insert(['id' => 3312, 'provinces_id' => 33, 'domisili_name' => 'WONOGIRI',]);
        DB::table('id_domisilis')->insert(['id' => 3313, 'provinces_id' => 33, 'domisili_name' => 'KARANGANYAR',]);
        DB::table('id_domisilis')->insert(['id' => 3314, 'provinces_id' => 33, 'domisili_name' => 'SRAGEN',]);
        DB::table('id_domisilis')->insert(['id' => 3315, 'provinces_id' => 33, 'domisili_name' => 'GROBOGAN',]);
        DB::table('id_domisilis')->insert(['id' => 3316, 'provinces_id' => 33, 'domisili_name' => 'BLORA',]);
        DB::table('id_domisilis')->insert(['id' => 3317, 'provinces_id' => 33, 'domisili_name' => 'REMBANG',]);
        DB::table('id_domisilis')->insert(['id' => 3318, 'provinces_id' => 33, 'domisili_name' => 'PATI',]);
        DB::table('id_domisilis')->insert(['id' => 3319, 'provinces_id' => 33, 'domisili_name' => 'KUDUS',]);
        DB::table('id_domisilis')->insert(['id' => 3320, 'provinces_id' => 33, 'domisili_name' => 'JEPARA',]);
        DB::table('id_domisilis')->insert(['id' => 3321, 'provinces_id' => 33, 'domisili_name' => 'DEMAK',]);
        DB::table('id_domisilis')->insert(['id' => 3322, 'provinces_id' => 33, 'domisili_name' => 'SEMARANG',]);
        DB::table('id_domisilis')->insert(['id' => 3323, 'provinces_id' => 33, 'domisili_name' => 'TEMANGGUNG',]);
        DB::table('id_domisilis')->insert(['id' => 3324, 'provinces_id' => 33, 'domisili_name' => 'KENDAL',]);
        DB::table('id_domisilis')->insert(['id' => 3325, 'provinces_id' => 33, 'domisili_name' => 'BATANG',]);
        DB::table('id_domisilis')->insert(['id' => 3326, 'provinces_id' => 33, 'domisili_name' => 'PEKALONGAN',]);
        DB::table('id_domisilis')->insert(['id' => 3327, 'provinces_id' => 33, 'domisili_name' => 'PEMALANG',]);
        DB::table('id_domisilis')->insert(['id' => 3328, 'provinces_id' => 33, 'domisili_name' => 'TEGAL',]);
        DB::table('id_domisilis')->insert(['id' => 3329, 'provinces_id' => 33, 'domisili_name' => 'BREBES',]);
        DB::table('id_domisilis')->insert(['id' => 3371, 'provinces_id' => 33, 'domisili_name' => 'MAGELANG',]);
        DB::table('id_domisilis')->insert(['id' => 3372, 'provinces_id' => 33, 'domisili_name' => 'SURAKARTA',]);
        DB::table('id_domisilis')->insert(['id' => 3373, 'provinces_id' => 33, 'domisili_name' => 'SALATIGA',]);
        DB::table('id_domisilis')->insert(['id' => 3374, 'provinces_id' => 33, 'domisili_name' => 'SEMARANG',]);
        DB::table('id_domisilis')->insert(['id' => 3375, 'provinces_id' => 33, 'domisili_name' => 'PEKALONGAN',]);
        DB::table('id_domisilis')->insert(['id' => 3376, 'provinces_id' => 33, 'domisili_name' => 'TEGAL',]);
        DB::table('id_domisilis')->insert(['id' => 3401, 'provinces_id' => 34, 'domisili_name' => 'KULON PROGO',]);
        DB::table('id_domisilis')->insert(['id' => 3402, 'provinces_id' => 34, 'domisili_name' => 'BANTUL',]);
        DB::table('id_domisilis')->insert(['id' => 3403, 'provinces_id' => 34, 'domisili_name' => 'GUNUNG KIDUL',]);
        DB::table('id_domisilis')->insert(['id' => 3404, 'provinces_id' => 34, 'domisili_name' => 'SLEMAN',]);
        DB::table('id_domisilis')->insert(['id' => 3471, 'provinces_id' => 34, 'domisili_name' => 'YOGYAKARTA',]);
        DB::table('id_domisilis')->insert(['id' => 3501, 'provinces_id' => 35, 'domisili_name' => 'PACITAN',]);
        DB::table('id_domisilis')->insert(['id' => 3502, 'provinces_id' => 35, 'domisili_name' => 'PONOROGO',]);
        DB::table('id_domisilis')->insert(['id' => 3503, 'provinces_id' => 35, 'domisili_name' => 'TRENGGALEK',]);
        DB::table('id_domisilis')->insert(['id' => 3504, 'provinces_id' => 35, 'domisili_name' => 'TULUNGAGUNG',]);
        DB::table('id_domisilis')->insert(['id' => 3505, 'provinces_id' => 35, 'domisili_name' => 'BLITAR',]);
        DB::table('id_domisilis')->insert(['id' => 3506, 'provinces_id' => 35, 'domisili_name' => 'KEDIRI',]);
        DB::table('id_domisilis')->insert(['id' => 3507, 'provinces_id' => 35, 'domisili_name' => 'MALANG',]);
        DB::table('id_domisilis')->insert(['id' => 3508, 'provinces_id' => 35, 'domisili_name' => 'LUMAJANG',]);
        DB::table('id_domisilis')->insert(['id' => 3509, 'provinces_id' => 35, 'domisili_name' => 'JEMBER',]);
        DB::table('id_domisilis')->insert(['id' => 3510, 'provinces_id' => 35, 'domisili_name' => 'BANYUWANGI',]);
        DB::table('id_domisilis')->insert(['id' => 3511, 'provinces_id' => 35, 'domisili_name' => 'BONDOWOSO',]);
        DB::table('id_domisilis')->insert(['id' => 3512, 'provinces_id' => 35, 'domisili_name' => 'SITUBONDO',]);
        DB::table('id_domisilis')->insert(['id' => 3513, 'provinces_id' => 35, 'domisili_name' => 'PROBOLINGGO',]);
        DB::table('id_domisilis')->insert(['id' => 3514, 'provinces_id' => 35, 'domisili_name' => 'PASURUAN',]);
        DB::table('id_domisilis')->insert(['id' => 3515, 'provinces_id' => 35, 'domisili_name' => 'SIDOARJO',]);
        DB::table('id_domisilis')->insert(['id' => 3516, 'provinces_id' => 35, 'domisili_name' => 'MOJOKERTO',]);
        DB::table('id_domisilis')->insert(['id' => 3517, 'provinces_id' => 35, 'domisili_name' => 'JOMBANG',]);
        DB::table('id_domisilis')->insert(['id' => 3518, 'provinces_id' => 35, 'domisili_name' => 'NGANJUK',]);
        DB::table('id_domisilis')->insert(['id' => 3519, 'provinces_id' => 35, 'domisili_name' => 'MADIUN',]);
        DB::table('id_domisilis')->insert(['id' => 3520, 'provinces_id' => 35, 'domisili_name' => 'MAGETAN',]);
        DB::table('id_domisilis')->insert(['id' => 3521, 'provinces_id' => 35, 'domisili_name' => 'NGAWI',]);
        DB::table('id_domisilis')->insert(['id' => 3522, 'provinces_id' => 35, 'domisili_name' => 'BOJONEGORO',]);
        DB::table('id_domisilis')->insert(['id' => 3523, 'provinces_id' => 35, 'domisili_name' => 'TUBAN',]);
        DB::table('id_domisilis')->insert(['id' => 3524, 'provinces_id' => 35, 'domisili_name' => 'LAMONGAN',]);
        DB::table('id_domisilis')->insert(['id' => 3525, 'provinces_id' => 35, 'domisili_name' => 'GRESIK',]);
        DB::table('id_domisilis')->insert(['id' => 3526, 'provinces_id' => 35, 'domisili_name' => 'BANGKALAN',]);
        DB::table('id_domisilis')->insert(['id' => 3527, 'provinces_id' => 35, 'domisili_name' => 'SAMPANG',]);
        DB::table('id_domisilis')->insert(['id' => 3528, 'provinces_id' => 35, 'domisili_name' => 'PAMEKASAN',]);
        DB::table('id_domisilis')->insert(['id' => 3529, 'provinces_id' => 35, 'domisili_name' => 'SUMENEP',]);
        DB::table('id_domisilis')->insert(['id' => 3571, 'provinces_id' => 35, 'domisili_name' => 'KEDIRI',]);
        DB::table('id_domisilis')->insert(['id' => 3572, 'provinces_id' => 35, 'domisili_name' => 'BLITAR',]);
        DB::table('id_domisilis')->insert(['id' => 3573, 'provinces_id' => 35, 'domisili_name' => 'MALANG',]);
        DB::table('id_domisilis')->insert(['id' => 3574, 'provinces_id' => 35, 'domisili_name' => 'PROBOLINGGO',]);
        DB::table('id_domisilis')->insert(['id' => 3575, 'provinces_id' => 35, 'domisili_name' => 'PASURUAN',]);
        DB::table('id_domisilis')->insert(['id' => 3576, 'provinces_id' => 35, 'domisili_name' => 'MOJOKERTO',]);
        DB::table('id_domisilis')->insert(['id' => 3577, 'provinces_id' => 35, 'domisili_name' => 'MADIUN',]);
        DB::table('id_domisilis')->insert(['id' => 3578, 'provinces_id' => 35, 'domisili_name' => 'SURABAYA',]);
        DB::table('id_domisilis')->insert(['id' => 3579, 'provinces_id' => 35, 'domisili_name' => 'BATU',]);
        DB::table('id_domisilis')->insert(['id' => 3601, 'provinces_id' => 36, 'domisili_name' => 'PANDEGLANG',]);
        DB::table('id_domisilis')->insert(['id' => 3602, 'provinces_id' => 36, 'domisili_name' => 'LEBAK',]);
        DB::table('id_domisilis')->insert(['id' => 3603, 'provinces_id' => 36, 'domisili_name' => 'TANGERANG',]);
        DB::table('id_domisilis')->insert(['id' => 3604, 'provinces_id' => 36, 'domisili_name' => 'SERANG',]);
        DB::table('id_domisilis')->insert(['id' => 3671, 'provinces_id' => 36, 'domisili_name' => 'TANGERANG',]);
        DB::table('id_domisilis')->insert(['id' => 3672, 'provinces_id' => 36, 'domisili_name' => 'CILEGON',]);
        DB::table('id_domisilis')->insert(['id' => 3673, 'provinces_id' => 36, 'domisili_name' => 'SERANG',]);
        DB::table('id_domisilis')->insert(['id' => 3674, 'provinces_id' => 36, 'domisili_name' => 'TANGERANG SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 5101, 'provinces_id' => 51, 'domisili_name' => 'JEMBRANA',]);
        DB::table('id_domisilis')->insert(['id' => 5102, 'provinces_id' => 51, 'domisili_name' => 'TABANAN',]);
        DB::table('id_domisilis')->insert(['id' => 5103, 'provinces_id' => 51, 'domisili_name' => 'BADUNG',]);
        DB::table('id_domisilis')->insert(['id' => 5104, 'provinces_id' => 51, 'domisili_name' => 'GIANYAR',]);
        DB::table('id_domisilis')->insert(['id' => 5105, 'provinces_id' => 51, 'domisili_name' => 'KLUNGKUNG',]);
        DB::table('id_domisilis')->insert(['id' => 5106, 'provinces_id' => 51, 'domisili_name' => 'BANGLI',]);
        DB::table('id_domisilis')->insert(['id' => 5107, 'provinces_id' => 51, 'domisili_name' => 'KARANG ASEM',]);
        DB::table('id_domisilis')->insert(['id' => 5108, 'provinces_id' => 51, 'domisili_name' => 'BULELENG',]);
        DB::table('id_domisilis')->insert(['id' => 5171, 'provinces_id' => 51, 'domisili_name' => 'DENPASAR',]);
        DB::table('id_domisilis')->insert(['id' => 5201, 'provinces_id' => 52, 'domisili_name' => 'LOMBOK BARAT',]);
        DB::table('id_domisilis')->insert(['id' => 5202, 'provinces_id' => 52, 'domisili_name' => 'LOMBOK TENGAH',]);
        DB::table('id_domisilis')->insert(['id' => 5203, 'provinces_id' => 52, 'domisili_name' => 'LOMBOK TIMUR',]);
        DB::table('id_domisilis')->insert(['id' => 5204, 'provinces_id' => 52, 'domisili_name' => 'SUMBAWA',]);
        DB::table('id_domisilis')->insert(['id' => 5205, 'provinces_id' => 52, 'domisili_name' => 'DOMPU',]);
        DB::table('id_domisilis')->insert(['id' => 5206, 'provinces_id' => 52, 'domisili_name' => 'BIMA',]);
        DB::table('id_domisilis')->insert(['id' => 5207, 'provinces_id' => 52, 'domisili_name' => 'SUMBAWA BARAT',]);
        DB::table('id_domisilis')->insert(['id' => 5208, 'provinces_id' => 52, 'domisili_name' => 'LOMBOK UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 5271, 'provinces_id' => 52, 'domisili_name' => 'MATARAM',]);
        DB::table('id_domisilis')->insert(['id' => 5272, 'provinces_id' => 52, 'domisili_name' => 'BIMA',]);
        DB::table('id_domisilis')->insert(['id' => 5301, 'provinces_id' => 53, 'domisili_name' => 'SUMBA BARAT',]);
        DB::table('id_domisilis')->insert(['id' => 5302, 'provinces_id' => 53, 'domisili_name' => 'SUMBA TIMUR',]);
        DB::table('id_domisilis')->insert(['id' => 5303, 'provinces_id' => 53, 'domisili_name' => 'KUPANG',]);
        DB::table('id_domisilis')->insert(['id' => 5304, 'provinces_id' => 53, 'domisili_name' => 'TIMOR TENGAH SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 5305, 'provinces_id' => 53, 'domisili_name' => 'TIMOR TENGAH UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 5306, 'provinces_id' => 53, 'domisili_name' => 'BELU',]);
        DB::table('id_domisilis')->insert(['id' => 5307, 'provinces_id' => 53, 'domisili_name' => 'ALOR',]);
        DB::table('id_domisilis')->insert(['id' => 5308, 'provinces_id' => 53, 'domisili_name' => 'LEMBATA',]);
        DB::table('id_domisilis')->insert(['id' => 5309, 'provinces_id' => 53, 'domisili_name' => 'FLORES TIMUR',]);
        DB::table('id_domisilis')->insert(['id' => 5310, 'provinces_id' => 53, 'domisili_name' => 'SIKKA',]);
        DB::table('id_domisilis')->insert(['id' => 5311, 'provinces_id' => 53, 'domisili_name' => 'ENDE',]);
        DB::table('id_domisilis')->insert(['id' => 5312, 'provinces_id' => 53, 'domisili_name' => 'NGADA',]);
        DB::table('id_domisilis')->insert(['id' => 5313, 'provinces_id' => 53, 'domisili_name' => 'MANGGARAI',]);
        DB::table('id_domisilis')->insert(['id' => 5314, 'provinces_id' => 53, 'domisili_name' => 'ROTE NDAO',]);
        DB::table('id_domisilis')->insert(['id' => 5315, 'provinces_id' => 53, 'domisili_name' => 'MANGGARAI BARAT',]);
        DB::table('id_domisilis')->insert(['id' => 5316, 'provinces_id' => 53, 'domisili_name' => 'SUMBA TENGAH',]);
        DB::table('id_domisilis')->insert(['id' => 5317, 'provinces_id' => 53, 'domisili_name' => 'SUMBA BARAT DAYA',]);
        DB::table('id_domisilis')->insert(['id' => 5318, 'provinces_id' => 53, 'domisili_name' => 'NAGEKEO',]);
        DB::table('id_domisilis')->insert(['id' => 5319, 'provinces_id' => 53, 'domisili_name' => 'MANGGARAI TIMUR',]);
        DB::table('id_domisilis')->insert(['id' => 5320, 'provinces_id' => 53, 'domisili_name' => 'SABU RAIJUA',]);
        DB::table('id_domisilis')->insert(['id' => 5321, 'provinces_id' => 53, 'domisili_name' => 'MALAKA',]);
        DB::table('id_domisilis')->insert(['id' => 5371, 'provinces_id' => 53, 'domisili_name' => 'KUPANG',]);
        DB::table('id_domisilis')->insert(['id' => 6101, 'provinces_id' => 61, 'domisili_name' => 'SAMBAS',]);
        DB::table('id_domisilis')->insert(['id' => 6102, 'provinces_id' => 61, 'domisili_name' => 'BENGKAYANG',]);
        DB::table('id_domisilis')->insert(['id' => 6103, 'provinces_id' => 61, 'domisili_name' => 'LANDAK',]);
        DB::table('id_domisilis')->insert(['id' => 6104, 'provinces_id' => 61, 'domisili_name' => 'MEMPAWAH',]);
        DB::table('id_domisilis')->insert(['id' => 6105, 'provinces_id' => 61, 'domisili_name' => 'SANGGAU',]);
        DB::table('id_domisilis')->insert(['id' => 6106, 'provinces_id' => 61, 'domisili_name' => 'KETAPANG',]);
        DB::table('id_domisilis')->insert(['id' => 6107, 'provinces_id' => 61, 'domisili_name' => 'SINTANG',]);
        DB::table('id_domisilis')->insert(['id' => 6108, 'provinces_id' => 61, 'domisili_name' => 'KAPUAS HULU',]);
        DB::table('id_domisilis')->insert(['id' => 6109, 'provinces_id' => 61, 'domisili_name' => 'SEKADAU',]);
        DB::table('id_domisilis')->insert(['id' => 6110, 'provinces_id' => 61, 'domisili_name' => 'MELAWI',]);
        DB::table('id_domisilis')->insert(['id' => 6111, 'provinces_id' => 61, 'domisili_name' => 'KAYONG UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 6112, 'provinces_id' => 61, 'domisili_name' => 'KUBU RAYA',]);
        DB::table('id_domisilis')->insert(['id' => 6171, 'provinces_id' => 61, 'domisili_name' => 'PONTIANAK',]);
        DB::table('id_domisilis')->insert(['id' => 6172, 'provinces_id' => 61, 'domisili_name' => 'SINGKAWANG',]);
        DB::table('id_domisilis')->insert(['id' => 6201, 'provinces_id' => 62, 'domisili_name' => 'KOTAWARINGIN BARAT',]);
        DB::table('id_domisilis')->insert(['id' => 6202, 'provinces_id' => 62, 'domisili_name' => 'KOTAWARINGIN TIMUR',]);
        DB::table('id_domisilis')->insert(['id' => 6203, 'provinces_id' => 62, 'domisili_name' => 'KAPUAS',]);
        DB::table('id_domisilis')->insert(['id' => 6204, 'provinces_id' => 62, 'domisili_name' => 'BARITO SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 6205, 'provinces_id' => 62, 'domisili_name' => 'BARITO UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 6206, 'provinces_id' => 62, 'domisili_name' => 'SUKAMARA',]);
        DB::table('id_domisilis')->insert(['id' => 6207, 'provinces_id' => 62, 'domisili_name' => 'LAMANDAU',]);
        DB::table('id_domisilis')->insert(['id' => 6208, 'provinces_id' => 62, 'domisili_name' => 'SERUYAN',]);
        DB::table('id_domisilis')->insert(['id' => 6209, 'provinces_id' => 62, 'domisili_name' => 'KATINGAN',]);
        DB::table('id_domisilis')->insert(['id' => 6210, 'provinces_id' => 62, 'domisili_name' => 'PULANG PISAU',]);
        DB::table('id_domisilis')->insert(['id' => 6211, 'provinces_id' => 62, 'domisili_name' => 'GUNUNG MAS',]);
        DB::table('id_domisilis')->insert(['id' => 6212, 'provinces_id' => 62, 'domisili_name' => 'BARITO TIMUR',]);
        DB::table('id_domisilis')->insert(['id' => 6213, 'provinces_id' => 62, 'domisili_name' => 'MURUNG RAYA',]);
        DB::table('id_domisilis')->insert(['id' => 6271, 'provinces_id' => 62, 'domisili_name' => 'PALANGKA RAYA',]);
        DB::table('id_domisilis')->insert(['id' => 6301, 'provinces_id' => 63, 'domisili_name' => 'TANAH LAUT',]);
        DB::table('id_domisilis')->insert(['id' => 6302, 'provinces_id' => 63, 'domisili_name' => 'BARU',]);
        DB::table('id_domisilis')->insert(['id' => 6303, 'provinces_id' => 63, 'domisili_name' => 'BANJAR',]);
        DB::table('id_domisilis')->insert(['id' => 6304, 'provinces_id' => 63, 'domisili_name' => 'BARITO KUALA',]);
        DB::table('id_domisilis')->insert(['id' => 6305, 'provinces_id' => 63, 'domisili_name' => 'TAPIN',]);
        DB::table('id_domisilis')->insert(['id' => 6306, 'provinces_id' => 63, 'domisili_name' => 'HULU SUNGAI SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 6307, 'provinces_id' => 63, 'domisili_name' => 'HULU SUNGAI TENGAH',]);
        DB::table('id_domisilis')->insert(['id' => 6308, 'provinces_id' => 63, 'domisili_name' => 'HULU SUNGAI UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 6309, 'provinces_id' => 63, 'domisili_name' => 'TABALONG',]);
        DB::table('id_domisilis')->insert(['id' => 6310, 'provinces_id' => 63, 'domisili_name' => 'TANAH BUMBU',]);
        DB::table('id_domisilis')->insert(['id' => 6311, 'provinces_id' => 63, 'domisili_name' => 'BALANGAN',]);
        DB::table('id_domisilis')->insert(['id' => 6371, 'provinces_id' => 63, 'domisili_name' => 'BANJARMASIN',]);
        DB::table('id_domisilis')->insert(['id' => 6372, 'provinces_id' => 63, 'domisili_name' => 'BANJAR BARU',]);
        DB::table('id_domisilis')->insert(['id' => 6401, 'provinces_id' => 64, 'domisili_name' => 'PASER',]);
        DB::table('id_domisilis')->insert(['id' => 6402, 'provinces_id' => 64, 'domisili_name' => 'KUTAI BARAT',]);
        DB::table('id_domisilis')->insert(['id' => 6403, 'provinces_id' => 64, 'domisili_name' => 'KUTAI KARTANEGARA',]);
        DB::table('id_domisilis')->insert(['id' => 6404, 'provinces_id' => 64, 'domisili_name' => 'KUTAI TIMUR',]);
        DB::table('id_domisilis')->insert(['id' => 6405, 'provinces_id' => 64, 'domisili_name' => 'BERAU',]);
        DB::table('id_domisilis')->insert(['id' => 6409, 'provinces_id' => 64, 'domisili_name' => 'PENAJAM PASER UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 6411, 'provinces_id' => 64, 'domisili_name' => 'MAHAKAM HULU',]);
        DB::table('id_domisilis')->insert(['id' => 6471, 'provinces_id' => 64, 'domisili_name' => 'BALIKPAPAN',]);
        DB::table('id_domisilis')->insert(['id' => 6472, 'provinces_id' => 64, 'domisili_name' => 'SAMARINDA',]);
        DB::table('id_domisilis')->insert(['id' => 6474, 'provinces_id' => 64, 'domisili_name' => 'BONTANG',]);
        DB::table('id_domisilis')->insert(['id' => 6501, 'provinces_id' => 65, 'domisili_name' => 'MALINAU',]);
        DB::table('id_domisilis')->insert(['id' => 6502, 'provinces_id' => 65, 'domisili_name' => 'BULUNGAN',]);
        DB::table('id_domisilis')->insert(['id' => 6503, 'provinces_id' => 65, 'domisili_name' => 'TANA TIDUNG',]);
        DB::table('id_domisilis')->insert(['id' => 6504, 'provinces_id' => 65, 'domisili_name' => 'NUNUKAN',]);
        DB::table('id_domisilis')->insert(['id' => 6571, 'provinces_id' => 65, 'domisili_name' => 'TARAKAN',]);
        DB::table('id_domisilis')->insert(['id' => 7101, 'provinces_id' => 71, 'domisili_name' => 'BOLAANG MONGONDOW',]);
        DB::table('id_domisilis')->insert(['id' => 7102, 'provinces_id' => 71, 'domisili_name' => 'MINAHASA',]);
        DB::table('id_domisilis')->insert(['id' => 7103, 'provinces_id' => 71, 'domisili_name' => 'KEPULAUAN SANGIHE',]);
        DB::table('id_domisilis')->insert(['id' => 7104, 'provinces_id' => 71, 'domisili_name' => 'KEPULAUAN TALAUD',]);
        DB::table('id_domisilis')->insert(['id' => 7105, 'provinces_id' => 71, 'domisili_name' => 'MINAHASA SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 7106, 'provinces_id' => 71, 'domisili_name' => 'MINAHASA UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 7107, 'provinces_id' => 71, 'domisili_name' => 'BOLAANG MONGONDOW UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 7108, 'provinces_id' => 71, 'domisili_name' => 'SIAU TAGULANDANG BIARO',]);
        DB::table('id_domisilis')->insert(['id' => 7109, 'provinces_id' => 71, 'domisili_name' => 'MINAHASA TENGGARA',]);
        DB::table('id_domisilis')->insert(['id' => 7110, 'provinces_id' => 71, 'domisili_name' => 'BOLAANG MONGONDOW SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 7111, 'provinces_id' => 71, 'domisili_name' => 'BOLAANG MONGONDOW TIMUR',]);
        DB::table('id_domisilis')->insert(['id' => 7171, 'provinces_id' => 71, 'domisili_name' => 'MANADO',]);
        DB::table('id_domisilis')->insert(['id' => 7172, 'provinces_id' => 71, 'domisili_name' => 'BITUNG',]);
        DB::table('id_domisilis')->insert(['id' => 7173, 'provinces_id' => 71, 'domisili_name' => 'TOMOHON',]);
        DB::table('id_domisilis')->insert(['id' => 7174, 'provinces_id' => 71, 'domisili_name' => 'KOTAMOBAGU',]);
        DB::table('id_domisilis')->insert(['id' => 7201, 'provinces_id' => 72, 'domisili_name' => 'BANGGAI KEPULAUAN',]);
        DB::table('id_domisilis')->insert(['id' => 7202, 'provinces_id' => 72, 'domisili_name' => 'BANGGAI',]);
        DB::table('id_domisilis')->insert(['id' => 7203, 'provinces_id' => 72, 'domisili_name' => 'MOROWALI',]);
        DB::table('id_domisilis')->insert(['id' => 7204, 'provinces_id' => 72, 'domisili_name' => 'POSO',]);
        DB::table('id_domisilis')->insert(['id' => 7205, 'provinces_id' => 72, 'domisili_name' => 'DONGGALA',]);
        DB::table('id_domisilis')->insert(['id' => 7206, 'provinces_id' => 72, 'domisili_name' => 'TOLI-TOLI',]);
        DB::table('id_domisilis')->insert(['id' => 7207, 'provinces_id' => 72, 'domisili_name' => 'BUOL',]);
        DB::table('id_domisilis')->insert(['id' => 7208, 'provinces_id' => 72, 'domisili_name' => 'PARIGI MOUTONG',]);
        DB::table('id_domisilis')->insert(['id' => 7209, 'provinces_id' => 72, 'domisili_name' => 'TOJO UNA-UNA',]);
        DB::table('id_domisilis')->insert(['id' => 7210, 'provinces_id' => 72, 'domisili_name' => 'SIGI',]);
        DB::table('id_domisilis')->insert(['id' => 7211, 'provinces_id' => 72, 'domisili_name' => 'BANGGAI LAUT',]);
        DB::table('id_domisilis')->insert(['id' => 7212, 'provinces_id' => 72, 'domisili_name' => 'MOROWALI UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 7271, 'provinces_id' => 72, 'domisili_name' => 'PALU',]);
        DB::table('id_domisilis')->insert(['id' => 7301, 'provinces_id' => 73, 'domisili_name' => 'KEPULAUAN SELAYAR',]);
        DB::table('id_domisilis')->insert(['id' => 7302, 'provinces_id' => 73, 'domisili_name' => 'BULUKUMBA',]);
        DB::table('id_domisilis')->insert(['id' => 7303, 'provinces_id' => 73, 'domisili_name' => 'BANTAENG',]);
        DB::table('id_domisilis')->insert(['id' => 7304, 'provinces_id' => 73, 'domisili_name' => 'JENEPONTO',]);
        DB::table('id_domisilis')->insert(['id' => 7305, 'provinces_id' => 73, 'domisili_name' => 'TAKALAR',]);
        DB::table('id_domisilis')->insert(['id' => 7306, 'provinces_id' => 73, 'domisili_name' => 'GOWA',]);
        DB::table('id_domisilis')->insert(['id' => 7307, 'provinces_id' => 73, 'domisili_name' => 'SINJAI',]);
        DB::table('id_domisilis')->insert(['id' => 7308, 'provinces_id' => 73, 'domisili_name' => 'MAROS',]);
        DB::table('id_domisilis')->insert(['id' => 7309, 'provinces_id' => 73, 'domisili_name' => 'PANGKAJENE DAN KEPULAUAN',]);
        DB::table('id_domisilis')->insert(['id' => 7310, 'provinces_id' => 73, 'domisili_name' => 'BARRU',]);
        DB::table('id_domisilis')->insert(['id' => 7311, 'provinces_id' => 73, 'domisili_name' => 'BONE',]);
        DB::table('id_domisilis')->insert(['id' => 7312, 'provinces_id' => 73, 'domisili_name' => 'SOPPENG',]);
        DB::table('id_domisilis')->insert(['id' => 7313, 'provinces_id' => 73, 'domisili_name' => 'WAJO',]);
        DB::table('id_domisilis')->insert(['id' => 7314, 'provinces_id' => 73, 'domisili_name' => 'SIDENRENG RAPPANG',]);
        DB::table('id_domisilis')->insert(['id' => 7315, 'provinces_id' => 73, 'domisili_name' => 'PINRANG',]);
        DB::table('id_domisilis')->insert(['id' => 7316, 'provinces_id' => 73, 'domisili_name' => 'ENREKANG',]);
        DB::table('id_domisilis')->insert(['id' => 7317, 'provinces_id' => 73, 'domisili_name' => 'LUWU',]);
        DB::table('id_domisilis')->insert(['id' => 7318, 'provinces_id' => 73, 'domisili_name' => 'TANA TORAJA',]);
        DB::table('id_domisilis')->insert(['id' => 7322, 'provinces_id' => 73, 'domisili_name' => 'LUWU UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 7325, 'provinces_id' => 73, 'domisili_name' => 'LUWU TIMUR',]);
        DB::table('id_domisilis')->insert(['id' => 7326, 'provinces_id' => 73, 'domisili_name' => 'TORAJA UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 7371, 'provinces_id' => 73, 'domisili_name' => 'MAKASSAR',]);
        DB::table('id_domisilis')->insert(['id' => 7372, 'provinces_id' => 73, 'domisili_name' => 'PAREPARE',]);
        DB::table('id_domisilis')->insert(['id' => 7373, 'provinces_id' => 73, 'domisili_name' => 'PALOPO',]);
        DB::table('id_domisilis')->insert(['id' => 7401, 'provinces_id' => 74, 'domisili_name' => 'BUTON',]);
        DB::table('id_domisilis')->insert(['id' => 7402, 'provinces_id' => 74, 'domisili_name' => 'MUNA',]);
        DB::table('id_domisilis')->insert(['id' => 7403, 'provinces_id' => 74, 'domisili_name' => 'KONAWE',]);
        DB::table('id_domisilis')->insert(['id' => 7404, 'provinces_id' => 74, 'domisili_name' => 'KOLAKA',]);
        DB::table('id_domisilis')->insert(['id' => 7405, 'provinces_id' => 74, 'domisili_name' => 'KONAWE SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 7406, 'provinces_id' => 74, 'domisili_name' => 'BOMBANA',]);
        DB::table('id_domisilis')->insert(['id' => 7407, 'provinces_id' => 74, 'domisili_name' => 'WAKATOBI',]);
        DB::table('id_domisilis')->insert(['id' => 7408, 'provinces_id' => 74, 'domisili_name' => 'KOLAKA UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 7409, 'provinces_id' => 74, 'domisili_name' => 'BUTON UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 7410, 'provinces_id' => 74, 'domisili_name' => 'KONAWE UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 7411, 'provinces_id' => 74, 'domisili_name' => 'KOLAKA TIMUR',]);
        DB::table('id_domisilis')->insert(['id' => 7412, 'provinces_id' => 74, 'domisili_name' => 'KONAWE KEPULAUAN',]);
        DB::table('id_domisilis')->insert(['id' => 7413, 'provinces_id' => 74, 'domisili_name' => 'MUNA BARAT',]);
        DB::table('id_domisilis')->insert(['id' => 7414, 'provinces_id' => 74, 'domisili_name' => 'BUTON TENGAH',]);
        DB::table('id_domisilis')->insert(['id' => 7415, 'provinces_id' => 74, 'domisili_name' => 'BUTON SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 7471, 'provinces_id' => 74, 'domisili_name' => 'KENDARI',]);
        DB::table('id_domisilis')->insert(['id' => 7472, 'provinces_id' => 74, 'domisili_name' => 'BAUBAU',]);
        DB::table('id_domisilis')->insert(['id' => 7501, 'provinces_id' => 75, 'domisili_name' => 'BOALEMO',]);
        DB::table('id_domisilis')->insert(['id' => 7502, 'provinces_id' => 75, 'domisili_name' => 'GORONTALO',]);
        DB::table('id_domisilis')->insert(['id' => 7503, 'provinces_id' => 75, 'domisili_name' => 'POHUWATO',]);
        DB::table('id_domisilis')->insert(['id' => 7504, 'provinces_id' => 75, 'domisili_name' => 'BONE BOLANGO',]);
        DB::table('id_domisilis')->insert(['id' => 7505, 'provinces_id' => 75, 'domisili_name' => 'GORONTALO UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 7571, 'provinces_id' => 75, 'domisili_name' => 'GORONTALO',]);
        DB::table('id_domisilis')->insert(['id' => 7601, 'provinces_id' => 76, 'domisili_name' => 'MAJENE',]);
        DB::table('id_domisilis')->insert(['id' => 7602, 'provinces_id' => 76, 'domisili_name' => 'POLEWALI MANDAR',]);
        DB::table('id_domisilis')->insert(['id' => 7603, 'provinces_id' => 76, 'domisili_name' => 'MAMASA',]);
        DB::table('id_domisilis')->insert(['id' => 7604, 'provinces_id' => 76, 'domisili_name' => 'MAMUJU',]);
        DB::table('id_domisilis')->insert(['id' => 7605, 'provinces_id' => 76, 'domisili_name' => 'MAMUJU UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 7606, 'provinces_id' => 76, 'domisili_name' => 'MAMUJU TENGAH',]);
        DB::table('id_domisilis')->insert(['id' => 8101, 'provinces_id' => 81, 'domisili_name' => 'MALUKU TENGGARA BARAT',]);
        DB::table('id_domisilis')->insert(['id' => 8102, 'provinces_id' => 81, 'domisili_name' => 'MALUKU TENGGARA',]);
        DB::table('id_domisilis')->insert(['id' => 8103, 'provinces_id' => 81, 'domisili_name' => 'MALUKU TENGAH',]);
        DB::table('id_domisilis')->insert(['id' => 8104, 'provinces_id' => 81, 'domisili_name' => 'BURU',]);
        DB::table('id_domisilis')->insert(['id' => 8105, 'provinces_id' => 81, 'domisili_name' => 'KEPULAUAN ARU',]);
        DB::table('id_domisilis')->insert(['id' => 8106, 'provinces_id' => 81, 'domisili_name' => 'SERAM BAGIAN BARAT',]);
        DB::table('id_domisilis')->insert(['id' => 8107, 'provinces_id' => 81, 'domisili_name' => 'SERAM BAGIAN TIMUR',]);
        DB::table('id_domisilis')->insert(['id' => 8108, 'provinces_id' => 81, 'domisili_name' => 'MALUKU BARAT DAYA',]);
        DB::table('id_domisilis')->insert(['id' => 8109, 'provinces_id' => 81, 'domisili_name' => 'BURU SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 8171, 'provinces_id' => 81, 'domisili_name' => 'AMBON',]);
        DB::table('id_domisilis')->insert(['id' => 8172, 'provinces_id' => 81, 'domisili_name' => 'TUAL',]);
        DB::table('id_domisilis')->insert(['id' => 8201, 'provinces_id' => 82, 'domisili_name' => 'HALMAHERA BARAT',]);
        DB::table('id_domisilis')->insert(['id' => 8202, 'provinces_id' => 82, 'domisili_name' => 'HALMAHERA TENGAH',]);
        DB::table('id_domisilis')->insert(['id' => 8203, 'provinces_id' => 82, 'domisili_name' => 'KEPULAUAN SULA',]);
        DB::table('id_domisilis')->insert(['id' => 8204, 'provinces_id' => 82, 'domisili_name' => 'HALMAHERA SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 8205, 'provinces_id' => 82, 'domisili_name' => 'HALMAHERA UTARA',]);
        DB::table('id_domisilis')->insert(['id' => 8206, 'provinces_id' => 82, 'domisili_name' => 'HALMAHERA TIMUR',]);
        DB::table('id_domisilis')->insert(['id' => 8207, 'provinces_id' => 82, 'domisili_name' => 'PULAU MOROTAI',]);
        DB::table('id_domisilis')->insert(['id' => 8208, 'provinces_id' => 82, 'domisili_name' => 'PULAU TALIABU',]);
        DB::table('id_domisilis')->insert(['id' => 8271, 'provinces_id' => 82, 'domisili_name' => 'TERNATE',]);
        DB::table('id_domisilis')->insert(['id' => 8272, 'provinces_id' => 82, 'domisili_name' => 'TIDORE KEPULAUAN',]);
        DB::table('id_domisilis')->insert(['id' => 9101, 'provinces_id' => 91, 'domisili_name' => 'FAKFAK',]);
        DB::table('id_domisilis')->insert(['id' => 9102, 'provinces_id' => 91, 'domisili_name' => 'KAIMANA',]);
        DB::table('id_domisilis')->insert(['id' => 9103, 'provinces_id' => 91, 'domisili_name' => 'TELUK WONDAMA',]);
        DB::table('id_domisilis')->insert(['id' => 9104, 'provinces_id' => 91, 'domisili_name' => 'TELUK BINTUNI',]);
        DB::table('id_domisilis')->insert(['id' => 9105, 'provinces_id' => 91, 'domisili_name' => 'MANOKWARI',]);
        DB::table('id_domisilis')->insert(['id' => 9106, 'provinces_id' => 91, 'domisili_name' => 'SORONG SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 9107, 'provinces_id' => 91, 'domisili_name' => 'SORONG',]);
        DB::table('id_domisilis')->insert(['id' => 9108, 'provinces_id' => 91, 'domisili_name' => 'RAJA AMPAT',]);
        DB::table('id_domisilis')->insert(['id' => 9109, 'provinces_id' => 91, 'domisili_name' => 'TAMBRAUW',]);
        DB::table('id_domisilis')->insert(['id' => 9110, 'provinces_id' => 91, 'domisili_name' => 'MAYBRAT',]);
        DB::table('id_domisilis')->insert(['id' => 9111, 'provinces_id' => 91, 'domisili_name' => 'MANOKWARI SELATAN',]);
        DB::table('id_domisilis')->insert(['id' => 9112, 'provinces_id' => 91, 'domisili_name' => 'PEGUNUNGAN ARFAK',]);
        DB::table('id_domisilis')->insert(['id' => 9171, 'provinces_id' => 91, 'domisili_name' => 'SORONG',]);
        DB::table('id_domisilis')->insert(['id' => 9401, 'provinces_id' => 94, 'domisili_name' => 'MERAUKE',]);
        DB::table('id_domisilis')->insert(['id' => 9402, 'provinces_id' => 94, 'domisili_name' => 'JAYAWIJAYA',]);
        DB::table('id_domisilis')->insert(['id' => 9403, 'provinces_id' => 94, 'domisili_name' => 'JAYAPURA',]);
        DB::table('id_domisilis')->insert(['id' => 9404, 'provinces_id' => 94, 'domisili_name' => 'NABIRE',]);
        DB::table('id_domisilis')->insert(['id' => 9408, 'provinces_id' => 94, 'domisili_name' => 'KEPULAUAN YAPEN',]);
        DB::table('id_domisilis')->insert(['id' => 9409, 'provinces_id' => 94, 'domisili_name' => 'BIAK NUMFOR',]);
        DB::table('id_domisilis')->insert(['id' => 9410, 'provinces_id' => 94, 'domisili_name' => 'PANIAI',]);
        DB::table('id_domisilis')->insert(['id' => 9411, 'provinces_id' => 94, 'domisili_name' => 'PUNCAK JAYA',]);
        DB::table('id_domisilis')->insert(['id' => 9412, 'provinces_id' => 94, 'domisili_name' => 'MIMIKA',]);
        DB::table('id_domisilis')->insert(['id' => 9413, 'provinces_id' => 94, 'domisili_name' => 'BOVEN DIGOEL',]);
        DB::table('id_domisilis')->insert(['id' => 9414, 'provinces_id' => 94, 'domisili_name' => 'MAPPI',]);
        DB::table('id_domisilis')->insert(['id' => 9415, 'provinces_id' => 94, 'domisili_name' => 'ASMAT',]);
        DB::table('id_domisilis')->insert(['id' => 9416, 'provinces_id' => 94, 'domisili_name' => 'YAHUKIMO',]);
        DB::table('id_domisilis')->insert(['id' => 9417, 'provinces_id' => 94, 'domisili_name' => 'PEGUNUNGAN BINTANG',]);
        DB::table('id_domisilis')->insert(['id' => 9418, 'provinces_id' => 94, 'domisili_name' => 'TOLIKARA',]);
        DB::table('id_domisilis')->insert(['id' => 9419, 'provinces_id' => 94, 'domisili_name' => 'SARMI',]);
        DB::table('id_domisilis')->insert(['id' => 9420, 'provinces_id' => 94, 'domisili_name' => 'KEEROM',]);
        DB::table('id_domisilis')->insert(['id' => 9426, 'provinces_id' => 94, 'domisili_name' => 'WAROPEN',]);
        DB::table('id_domisilis')->insert(['id' => 9427, 'provinces_id' => 94, 'domisili_name' => 'SUPIORI',]);
        DB::table('id_domisilis')->insert(['id' => 9428, 'provinces_id' => 94, 'domisili_name' => 'MAMBERAMO RAYA',]);
        DB::table('id_domisilis')->insert(['id' => 9429, 'provinces_id' => 94, 'domisili_name' => 'NDUGA',]);
        DB::table('id_domisilis')->insert(['id' => 9430, 'provinces_id' => 94, 'domisili_name' => 'LANNY JAYA',]);
        DB::table('id_domisilis')->insert(['id' => 9431, 'provinces_id' => 94, 'domisili_name' => 'MAMBERAMO TENGAH',]);
        DB::table('id_domisilis')->insert(['id' => 9432, 'provinces_id' => 94, 'domisili_name' => 'YALIMO',]);
        DB::table('id_domisilis')->insert(['id' => 9433, 'provinces_id' => 94, 'domisili_name' => 'PUNCAK',]);
        DB::table('id_domisilis')->insert(['id' => 9434, 'provinces_id' => 94, 'domisili_name' => 'DOGIYAI',]);
        DB::table('id_domisilis')->insert(['id' => 9435, 'provinces_id' => 94, 'domisili_name' => 'INTAN JAYA',]);
        DB::table('id_domisilis')->insert(['id' => 9436, 'provinces_id' => 94, 'domisili_name' => 'DEIYAI',]);
        DB::table('id_domisilis')->insert(['id' => 9471, 'provinces_id' => 94, 'domisili_name' => 'JAYAPURA',]);
    }
}
